### PR TITLE
Simple transposition added

### PR DESCRIPTION
**Pull request by vkhalaim**
Hi! I have added one method to the class and one test for it ) #12

### CODE REVIEW

**Comment by THargreaves** [comment]
Thank you. That's a nice approach and I appreciate the test coverage. Is there a reason you decided to modify the existing instance rather than creating a new one?

**Comment by vkhalaim** [comment]
It's just looked more mathematically for me :) But I can rewrite that method will return a new instance

**Comment by THargreaves** [comment]
I get where you're coming from. My thought process is that if you have it return a new instance then at least you can override the current instance with the pattern `m1 = m1.transpose()`. If we did it the other way round though you'd have to first copy a matrix to get its transpose in a new variable which seems long-winded.

Also I think this would be good for method changing. Something like `m1.transpose().row_reduce()` could eventually be possible. This could still work if you changed the instance then returned `self` but then you have to deal with matrices trying to print themselves whenever you transpose them. If only Python had something like R's `invisible()` function. 

Sorry for the ramble, just trying to collect my thoughts on the matter. Changing it to returning a new instance would be very helpful. Checkout the `init=False` argument of `__init__()` used in the existing class methods for what I believe is the most efficient way to do this. Cheers :)

**Comment by vkhalaim** [comment]
Please, look at the new version of transpose method :)

**Pull request merged**
